# Generated by Django 3.2.5 on 2021-08-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_leaderboard_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer_a', models.CharField(max_length=150)),
                ('answer_b', models.CharField(max_length=150)),
                ('answer_c', models.CharField(max_length=150)),
                ('answer_d', models.CharField(max_length=150)),
                ('good_answer', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.category')),
            ],
        ),
    ]
